import type { Course } from "@/types/course";

/**
 * Course catalogue.
 * Status must stay honest: "active" is used only where Carolina Academy has
 * confirmed the programme is currently running and taking applications.
 * Everything else is "upcoming" or "under-development" until confirmed.
 * See CMS_MIGRATION.md for how this maps to a future headless CMS collection.
 */

const REQUIRES_CONFIRMATION = "[REQUIRES CONFIRMATION]" as const;

export const courses: Course[] = [
  {
    id: "pastry-bakery-nvq-3-4",
    slug: "pastry-bakery-nvq-level-3-4",
    title: "Pastry & Bakery NVQ Level 3/4 Course",
    shortTitle: "Pastry & Bakery NVQ Level 3/4",
    category: "pastry-bakery",
    status: "active",
    qualification: "nvq",
    qualificationLabel: "Baker / Commis I — Pastry & Bakery",
    accreditation: {
      body: "TVEC",
      note:
        "Carolina Academy is a TVEC Registered Institution (Registration No. P13/0095). The NVQ status of this specific programme is displayed pending verification against the official TVEC course register — see the Accreditation section on the About page.",
    },
    courseCode: "D15S002",
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "practical-placement",
    location: "Carolina Beach Resort, Ambakandawila Road, Chilaw",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "The Pastry & Bakery NVQ Level 3/4 course prepares students for a career as a Baker or Commis I in the pastry and bakery trade. Training combines structured theory with hands-on practice in a working hospitality environment at Carolina Beach Resort, so students practise the same routines used in professional kitchens.",
    audience: [
      "School leavers who want a practical, career-focused qualification",
      "Individuals seeking to enter the hospitality and culinary industry",
      "Anyone wanting to build professional pastry and bakery skills for local or international employment",
    ],
    entryRequirements: [
      "Minimum age and educational requirements: [REQUIRES CONFIRMATION]",
      "Basic spoken and written English or Sinhala/Tamil proficiency: [REQUIRES CONFIRMATION]",
      "Any medical fitness requirement for kitchen-based practical training: [REQUIRES CONFIRMATION]",
    ],
    curriculum: [
      {
        category: "Workplace Safety & Hygiene",
        topics: ["Kitchen safety practices", "Personal hygiene standards", "Safe equipment handling"],
      },
      {
        category: "Food Safety",
        topics: ["Food handling standards", "Storage and temperature control", "Contamination prevention"],
      },
      {
        category: "Ingredients & Equipment",
        topics: ["Core baking ingredients", "Bakery and pastry equipment", "Equipment maintenance basics"],
      },
      {
        category: "Bread Production",
        topics: ["Dough preparation", "Fermentation and proofing", "Baking techniques"],
      },
      {
        category: "Cakes & Pastries",
        topics: ["Cake batters and methods", "Laminated and short pastry", "Fillings and creams"],
      },
      {
        category: "Desserts",
        topics: ["Hot and cold dessert preparation", "Plating fundamentals"],
      },
      {
        category: "Product Finishing & Decoration",
        topics: ["Icing and glazing", "Piping and decorative techniques", "Presentation standards"],
      },
      {
        category: "Cost Control & Production Planning",
        topics: ["Basic costing", "Portion control", "Production scheduling"],
      },
      {
        category: "Practical Assessments",
        topics: ["Supervised kitchen practicals", "Skills demonstrations", "Final competency assessment"],
      },
    ],
    curriculumNote:
      "Curriculum categories above are indicative and subject to the official programme syllabus. Confirm the current syllabus with Carolina Academy before enrolling.",
    practicalTraining:
      "Practical training takes place in a working hospitality environment at Carolina Beach Resort, giving students exposure to real kitchen operations alongside classroom-based instruction.",
    trainingVenue: "Hospitality Training Center, Carolina Beach Resort, Ambakandawila Road, Chilaw, Sri Lanka",
    assessment:
      "Assessment approach (continuous assessment, practical examinations, final competency assessment): [REQUIRES CONFIRMATION] against the official NVQ assessment guidelines.",
    careerOutcomes: [
      "Entry-level roles such as Baker or Commis I in hotel, resort and bakery kitchens",
      "A foundation for further pastry and culinary qualifications",
      "Employment-oriented skills applicable to local and, subject to individual eligibility, international hospitality employers",
    ],
    faqs: [
      {
        question: "What qualification will I receive?",
        answer:
          "The programme is structured around the Baker/Commis I — Pastry & Bakery competency profile (course code D15S002). The precise NVQ certification level and issuing details are displayed pending verification — confirm current status directly with Carolina Academy.",
      },
      {
        question: "Who can apply?",
        answer:
          "This course is intended for school leavers and career changers who want practical, hands-on training in pastry and bakery. Specific entry requirements are being confirmed — contact Carolina Academy for the latest criteria.",
      },
      {
        question: "How long is the programme?",
        answer: "Course duration is being confirmed. Contact Carolina Academy for the current schedule.",
      },
      {
        question: "Where is practical training conducted?",
        answer:
          "Practical training is conducted at Carolina Beach Resort, Ambakandawila Road, Chilaw, giving students exposure to a real hospitality kitchen environment.",
      },
      {
        question: "How much does the course cost?",
        answer: "Course fees are being confirmed. Contact Carolina Academy for current pricing.",
      },
      {
        question: "Can fees be paid in instalments?",
        answer:
          "Instalment plans, if offered, will be confirmed here. Please ask Carolina Academy directly about available payment options.",
      },
      {
        question: "What careers can I pursue?",
        answer:
          "Graduates are prepared for entry-level pastry and bakery roles such as Baker or Commis I in hotels, resorts and bakeries. Carolina Academy does not guarantee job placement; employment depends on individual performance and employer requirements.",
      },
      {
        question: "How do I apply?",
        answer:
          "Use the application form on this page, call the Hospitality Training Center on +94 77 383 1955, or message Carolina Academy on WhatsApp to begin the application process.",
      },
    ],
    featuredImage: {
      src: "/images/pastry-bakery-training.svg",
      alt: "Student practising pastry and bakery techniques in a training kitchen",
    },
    gallery: [
      { src: "/images/pastry-bakery-training.svg", alt: "Pastry and bakery practical training session" },
      { src: "/images/training-kitchen.svg", alt: "Training kitchen used for practical hospitality classes" },
      { src: "/images/carolina-beach-resort.svg", alt: "Carolina Beach Resort, the practical training venue" },
    ],
    applicationUrl: "/apply?course=pastry-bakery-nvq-level-3-4",
    whatsappMessage:
      "Hello Carolina Academy, I am interested in the Pastry and Bakery NVQ course.",
    updatedAt: "2026-08-04",
  },
  {
    id: "food-and-beverage-service",
    slug: "food-and-beverage-service",
    title: "Food & Beverage Service Training",
    shortTitle: "Food & Beverage Service",
    category: "food-beverage-service",
    status: "upcoming",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "practical-placement",
    location: "Carolina Beach Resort, Chilaw",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "A planned programme covering front-of-house food and beverage service skills for the hospitality industry, including table service, guest interaction and service-standard training. Full programme details are being finalised.",
    audience: ["Students interested in front-of-house hospitality careers"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "Full curriculum will be published once the programme is confirmed as active.",
    practicalTraining: "Planned to take place at Carolina Beach Resort, subject to confirmation.",
    trainingVenue: "Hospitality Training Center, Carolina Beach Resort, Ambakandawila Road, Chilaw, Sri Lanka",
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: ["Entry-level food and beverage service roles (subject to programme confirmation)"],
    faqs: [],
    featuredImage: {
      src: "/images/food-beverage-service.svg",
      alt: "Food and beverage service training placeholder image",
    },
    gallery: [],
    applicationUrl: "/contact?enquiry=food-and-beverage-service",
    whatsappMessage:
      "Hello Carolina Academy, I would like more information about the Food & Beverage Service programme.",
    updatedAt: "2026-08-04",
  },
  {
    id: "housekeeping",
    slug: "housekeeping",
    title: "Housekeeping Training",
    shortTitle: "Housekeeping",
    category: "housekeeping",
    status: "upcoming",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "practical-placement",
    location: "Carolina Beach Resort, Chilaw",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "A planned programme covering professional housekeeping standards for hotels and resorts, including room preparation, linen and laundry practices, and guest-service etiquette. Full programme details are being finalised.",
    audience: ["Students interested in hotel housekeeping and accommodation operations"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "Full curriculum will be published once the programme is confirmed as active.",
    practicalTraining: "Planned to take place at Carolina Beach Resort, subject to confirmation.",
    trainingVenue: "Hospitality Training Center, Carolina Beach Resort, Ambakandawila Road, Chilaw, Sri Lanka",
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: ["Entry-level housekeeping roles (subject to programme confirmation)"],
    faqs: [],
    featuredImage: { src: "/images/housekeeping-training.svg", alt: "Housekeeping training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=housekeeping",
    whatsappMessage: "Hello Carolina Academy, I would like more information about the Housekeeping programme.",
    updatedAt: "2026-08-04",
  },
  {
    id: "steward-training",
    slug: "steward-training",
    title: "Steward Training",
    shortTitle: "Steward Training",
    category: "hospitality",
    status: "upcoming",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "practical-placement",
    location: "Carolina Beach Resort, Chilaw",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "A planned programme introducing kitchen stewarding practices — cleanliness, equipment care and back-of-house support — for students entering hospitality kitchens.",
    audience: ["Students interested in kitchen support and back-of-house hospitality roles"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "Full curriculum will be published once the programme is confirmed as active.",
    practicalTraining: "Planned to take place at Carolina Beach Resort, subject to confirmation.",
    trainingVenue: "Hospitality Training Center, Carolina Beach Resort, Ambakandawila Road, Chilaw, Sri Lanka",
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: ["Entry-level kitchen steward roles (subject to programme confirmation)"],
    faqs: [],
    featuredImage: { src: "/images/steward-training.svg", alt: "Kitchen steward training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=steward-training",
    whatsappMessage: "Hello Carolina Academy, I would like more information about Steward Training.",
    updatedAt: "2026-08-04",
  },
  {
    id: "international-cookery",
    slug: "international-cookery",
    title: "International Cookery",
    shortTitle: "International Cookery",
    category: "hospitality",
    status: "upcoming",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "practical-placement",
    location: "Carolina Beach Resort, Chilaw",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "A planned culinary programme covering international cuisine techniques and kitchen operations for students pursuing a professional cookery career.",
    audience: ["Students interested in professional culinary careers"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "Full curriculum will be published once the programme is confirmed as active.",
    practicalTraining: "Planned to take place at Carolina Beach Resort, subject to confirmation.",
    trainingVenue: "Hospitality Training Center, Carolina Beach Resort, Ambakandawila Road, Chilaw, Sri Lanka",
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: ["Entry-level commis chef roles (subject to programme confirmation)"],
    faqs: [],
    featuredImage: { src: "/images/international-cookery.svg", alt: "International cookery training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=international-cookery",
    whatsappMessage: "Hello Carolina Academy, I would like more information about International Cookery.",
    updatedAt: "2026-08-04",
  },
  {
    id: "national-cookery",
    slug: "national-cookery",
    title: "National Cookery",
    shortTitle: "National Cookery",
    category: "hospitality",
    status: "upcoming",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "practical-placement",
    location: "Carolina Beach Resort, Chilaw",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "A planned culinary programme focused on Sri Lankan national cuisine, technique and kitchen operations for students pursuing a professional cookery career.",
    audience: ["Students interested in Sri Lankan culinary careers"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "Full curriculum will be published once the programme is confirmed as active.",
    practicalTraining: "Planned to take place at Carolina Beach Resort, subject to confirmation.",
    trainingVenue: "Hospitality Training Center, Carolina Beach Resort, Ambakandawila Road, Chilaw, Sri Lanka",
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: ["Entry-level commis chef roles (subject to programme confirmation)"],
    faqs: [],
    featuredImage: { src: "/images/national-cookery.svg", alt: "National cookery training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=national-cookery",
    whatsappMessage: "Hello Carolina Academy, I would like more information about National Cookery.",
    updatedAt: "2026-08-04",
  },
  {
    id: "electric-arc-welding",
    slug: "electric-arc-welding",
    title: "Electric Arc Welding",
    shortTitle: "Electric Arc Welding",
    category: "welding",
    status: "upcoming",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "on-campus",
    location: "Chilaw, Sri Lanka",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "A planned technical training programme introducing electric arc welding fundamentals, safety and workshop practice as part of Carolina Academy's growing Technology faculty.",
    audience: ["Students interested in technical and industrial trades"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "Full curriculum will be published once the programme is confirmed as active.",
    practicalTraining: "Workshop-based practical training location to be confirmed.",
    trainingVenue: REQUIRES_CONFIRMATION,
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: ["Entry-level welding and fabrication roles (subject to programme confirmation)"],
    faqs: [],
    featuredImage: { src: "/images/welding-training.svg", alt: "Electric arc welding training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=electric-arc-welding",
    whatsappMessage: "Hello Carolina Academy, I would like more information about Electric Arc Welding training.",
    updatedAt: "2026-08-04",
  },
  {
    id: "gas-welding",
    slug: "gas-welding",
    title: "Gas Welding",
    shortTitle: "Gas Welding",
    category: "welding",
    status: "under-development",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "on-campus",
    location: "Chilaw, Sri Lanka",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview: "Gas welding training is under development as part of Carolina Academy's Technology faculty.",
    audience: ["Students interested in technical and industrial trades"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "This programme is still under development. Details will be published once confirmed.",
    practicalTraining: "To be confirmed.",
    trainingVenue: REQUIRES_CONFIRMATION,
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: [],
    faqs: [],
    featuredImage: { src: "/images/welding-training.svg", alt: "Gas welding training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=gas-welding",
    whatsappMessage: "Hello Carolina Academy, I would like more information about Gas Welding training.",
    updatedAt: "2026-08-04",
  },
  {
    id: "mig-welding",
    slug: "mig-welding",
    title: "MIG Welding",
    shortTitle: "MIG Welding",
    category: "welding",
    status: "under-development",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "on-campus",
    location: "Chilaw, Sri Lanka",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "MIG (Metal Inert Gas) welding training, including 3G–6G position references, is under development as part of Carolina Academy's Technology faculty.",
    audience: ["Students interested in technical and industrial trades"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "This programme is still under development. Details will be published once confirmed.",
    practicalTraining: "To be confirmed.",
    trainingVenue: REQUIRES_CONFIRMATION,
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: [],
    faqs: [],
    featuredImage: { src: "/images/welding-training.svg", alt: "MIG welding training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=mig-welding",
    whatsappMessage: "Hello Carolina Academy, I would like more information about MIG Welding training.",
    updatedAt: "2026-08-04",
  },
  {
    id: "tig-welding",
    slug: "tig-welding",
    title: "TIG Welding",
    shortTitle: "TIG Welding",
    category: "welding",
    status: "under-development",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification type to be confirmed",
    accreditation: { body: "Not yet confirmed", note: "Accreditation details will be published once confirmed." },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "on-campus",
    location: "Chilaw, Sri Lanka",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "TIG (Tungsten Inert Gas) welding training, including 3G–6G position references, is under development as part of Carolina Academy's Technology faculty.",
    audience: ["Students interested in technical and industrial trades"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "This programme is still under development. Details will be published once confirmed.",
    practicalTraining: "To be confirmed.",
    trainingVenue: REQUIRES_CONFIRMATION,
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: [],
    faqs: [],
    featuredImage: { src: "/images/welding-training.svg", alt: "TIG welding training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=tig-welding",
    whatsappMessage: "Hello Carolina Academy, I would like more information about TIG Welding training.",
    updatedAt: "2026-08-04",
  },
  {
    id: "caregiver-training",
    slug: "caregiver-training",
    title: "Caregiver Training",
    shortTitle: "Caregiver Training",
    category: "health-sciences",
    status: "under-development",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification and regulatory approval to be confirmed",
    accreditation: {
      body: "Not yet confirmed",
      note:
        "No medical or healthcare licensing claim is made for this programme. Accreditation and regulatory approval details will be published once confirmed.",
    },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "on-campus",
    location: "Chilaw, Sri Lanka",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "Caregiver training is under development within Carolina Academy's Health Sciences faculty. This page will be updated with verified curriculum and accreditation details once the programme is finalised.",
    audience: ["Students interested in caregiving and support-worker roles"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "This programme is still under development. Details will be published once confirmed.",
    practicalTraining: "To be confirmed.",
    trainingVenue: REQUIRES_CONFIRMATION,
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: [],
    faqs: [],
    featuredImage: { src: "/images/health-sciences-training.svg", alt: "Caregiver training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=caregiver-training",
    whatsappMessage: "Hello Carolina Academy, I would like more information about Caregiver Training.",
    updatedAt: "2026-08-04",
  },
  {
    id: "nurse-assistant-training",
    slug: "nurse-assistant-training",
    title: "Nurse Assistant Training",
    shortTitle: "Nurse Assistant",
    category: "health-sciences",
    status: "under-development",
    qualification: "not-yet-confirmed",
    qualificationLabel: "Qualification and regulatory approval to be confirmed",
    accreditation: {
      body: "Not yet confirmed",
      note:
        "No medical or nursing licensing claim is made for this programme. Accreditation and regulatory approval details will be published once confirmed.",
    },
    duration: REQUIRES_CONFIRMATION,
    schedule: REQUIRES_CONFIRMATION,
    medium: REQUIRES_CONFIRMATION,
    deliveryType: "on-campus",
    location: "Chilaw, Sri Lanka",
    fee: REQUIRES_CONFIRMATION,
    instalments: REQUIRES_CONFIRMATION,
    nextIntake: REQUIRES_CONFIRMATION,
    overview:
      "Nurse Assistant training is under development within Carolina Academy's Health Sciences faculty. This page will be updated with verified curriculum and accreditation details once the programme is finalised.",
    audience: ["Students interested in healthcare support roles"],
    entryRequirements: [REQUIRES_CONFIRMATION],
    curriculum: [],
    curriculumNote: "This programme is still under development. Details will be published once confirmed.",
    practicalTraining: "To be confirmed.",
    trainingVenue: REQUIRES_CONFIRMATION,
    assessment: REQUIRES_CONFIRMATION,
    careerOutcomes: [],
    faqs: [],
    featuredImage: { src: "/images/health-sciences-training.svg", alt: "Nurse assistant training placeholder image" },
    gallery: [],
    applicationUrl: "/contact?enquiry=nurse-assistant-training",
    whatsappMessage: "Hello Carolina Academy, I would like more information about Nurse Assistant training.",
    updatedAt: "2026-08-04",
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((course) => course.slug === slug);
}

export function getCoursesByCategory(category: string): Course[] {
  if (category === "all") return courses;
  return courses.filter((course) => course.category === category);
}

export const courseCategoryLabels: Record<string, string> = {
  hospitality: "Hospitality",
  "pastry-bakery": "Pastry & Bakery",
  "food-beverage-service": "Food & Beverage Service",
  housekeeping: "Housekeeping",
  technology: "Technology",
  welding: "Welding",
  "health-sciences": "Health Sciences",
};

export const courseStatusLabels: Record<string, string> = {
  active: "Active Programme — Applications Open",
  upcoming: "Upcoming Programme — Details Subject to Confirmation",
  "under-development": "Under Development",
};
